from __future__ import annotations

import re
import string
from pathlib import Path
from typing import Any
from urllib.parse import urlparse


class LeagueContextError(ValueError):
    """Raised when league context cannot be resolved from Sleeper metadata."""


def extract_league_id(league_ref: str) -> str:
    """Extract a Sleeper league_id from a raw ID or Sleeper league URL."""
    value = league_ref.strip()
    if value.isdigit():
        return value

    parsed = urlparse(value)
    for segment in parsed.path.split("/"):
        if segment.isdigit():
            return segment

    match = re.search(r"\b\d{8,}\b", value)
    if match:
        return match.group(0)

    raise LeagueContextError(
        "Could not find a Sleeper league_id in the provided league URL or value."
    )


def resolve_league_context(
    client: Any,
    *,
    league_ref: str,
    team_name: str,
) -> dict[str, Any]:
    league_id = extract_league_id(league_ref)
    users = client.get_league_users(league_id)
    rosters = client.get_rosters(league_id)
    query = _normalize(team_name)

    if not query:
        raise LeagueContextError("team_name must not be empty")

    candidates = [
        _build_candidate(league_id=league_id, roster=roster, user=user)
        for roster in rosters
        for user in [_user_for_roster(users, roster)]
    ]

    exact_matches = _find_matches(candidates, query=query, mode="exact")
    if len(exact_matches) == 1:
        return _with_env(exact_matches[0])
    if len(exact_matches) > 1:
        raise LeagueContextError(_ambiguous_message(team_name, exact_matches))

    partial_matches = _find_matches(candidates, query=query, mode="partial")
    if len(partial_matches) == 1:
        return _with_env(partial_matches[0])
    if len(partial_matches) > 1:
        raise LeagueContextError(_ambiguous_message(team_name, partial_matches))

    raise LeagueContextError(
        f"No roster matched {team_name!r}. Available teams: "
        f"{', '.join(_candidate_label(candidate) for candidate in candidates)}"
    )


def render_context_env(context: dict[str, Any], *, league_ref: str | None = None) -> str:
    lines = ["# Generated by sleeper configure-context."]
    if league_ref:
        lines.append(f"SLEEPER_DEFAULT_LEAGUE_URL={_env_value(league_ref)}")
    lines.extend(
        [
            f"SLEEPER_DEFAULT_LEAGUE_ID={context['league_id']}",
            f"SLEEPER_DEFAULT_ROSTER_ID={context['roster_id']}",
        ]
    )
    if context.get("owner_id"):
        lines.append(f"SLEEPER_DEFAULT_OWNER_ID={context['owner_id']}")
    if context.get("team_name"):
        lines.append(f"SLEEPER_DEFAULT_TEAM_NAME={_env_value(context['team_name'])}")
    if context.get("display_name"):
        lines.append(
            f"SLEEPER_DEFAULT_DISPLAY_NAME={_env_value(context['display_name'])}"
        )
    if context.get("username"):
        lines.append(f"SLEEPER_DEFAULT_USERNAME={_env_value(context['username'])}")
    return "\n".join(lines) + "\n"


def write_context_env_file(
    context: dict[str, Any],
    env_file: Path,
    *,
    league_ref: str | None = None,
) -> None:
    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text(
        render_context_env(context, league_ref=league_ref),
        encoding="utf-8",
    )


def _build_candidate(
    *,
    league_id: str,
    roster: dict[str, Any],
    user: dict[str, Any],
) -> dict[str, Any]:
    user_metadata = _metadata(user)
    roster_metadata = _metadata(roster)
    owner_id = _string_or_empty(roster.get("owner_id"))
    user_id = _string_or_empty(user.get("user_id")) or owner_id
    roster_id = roster.get("roster_id")
    team_name = (
        _string_or_empty(user_metadata.get("team_name"))
        or _string_or_empty(roster_metadata.get("team_name"))
    )

    return {
        "league_id": league_id,
        "roster_id": roster_id,
        "owner_id": owner_id,
        "user_id": user_id,
        "display_name": _string_or_empty(user.get("display_name")),
        "username": _string_or_empty(user.get("username")),
        "team_name": team_name,
        "matched_on": "",
        "match_value": "",
    }


def _find_matches(
    candidates: list[dict[str, Any]],
    *,
    query: str,
    mode: str,
) -> list[dict[str, Any]]:
    matches = []
    for candidate in candidates:
        for field in (
            "team_name",
            "display_name",
            "username",
            "owner_id",
            "user_id",
            "roster_id",
        ):
            raw_value = candidate.get(field)
            normalized_value = _normalize(str(raw_value or ""))
            if not normalized_value:
                continue
            if mode == "exact" and normalized_value != query:
                continue
            if mode == "partial" and query not in normalized_value:
                continue
            matches.append(
                {**candidate, "matched_on": field, "match_value": raw_value}
            )
            break
    return matches


def _user_for_roster(
    users: list[dict[str, Any]],
    roster: dict[str, Any],
) -> dict[str, Any]:
    owner_id = str(roster.get("owner_id") or "")
    for user in users:
        if str(user.get("user_id") or "") == owner_id:
            return user
    return {}


def _with_env(context: dict[str, Any]) -> dict[str, Any]:
    return {
        **context,
        "env": {
            "SLEEPER_DEFAULT_LEAGUE_ID": str(context["league_id"]),
            "SLEEPER_DEFAULT_ROSTER_ID": str(context["roster_id"]),
            "SLEEPER_DEFAULT_OWNER_ID": str(context.get("owner_id") or ""),
        },
    }


def _ambiguous_message(team_name: str, matches: list[dict[str, Any]]) -> str:
    return (
        f"Multiple rosters matched {team_name!r}: "
        f"{', '.join(_candidate_label(match) for match in matches)}. "
        "Use a more specific team name, display name, roster_id, or owner_id."
    )


def _candidate_label(candidate: dict[str, Any]) -> str:
    team_name = candidate.get("team_name") or "(no team name)"
    display_name = candidate.get("display_name") or "(no display name)"
    return (
        f"roster_id={candidate.get('roster_id')} "
        f"team={team_name!r} display={display_name!r}"
    )


def _metadata(row: dict[str, Any]) -> dict[str, Any]:
    metadata = row.get("metadata")
    return metadata if isinstance(metadata, dict) else {}


def _normalize(value: str) -> str:
    lower = value.casefold().strip()
    return "".join(
        character
        for character in lower
        if character not in string.punctuation and not character.isspace()
    )


def _string_or_empty(value: Any) -> str:
    return "" if value is None else str(value)


def _env_value(value: Any) -> str:
    raw = str(value)
    escaped = (
        raw.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("`", "\\`")
    )
    return f'"{escaped}"'
