from __future__ import annotations

import pytest

from sleeper_tooling.league_context import (
    LeagueContextError,
    extract_league_id,
    render_context_env,
    resolve_league_context,
    write_context_env_file,
)


def test_extract_league_id_accepts_raw_id() -> None:
    assert extract_league_id("1389328071634460672") == "1389328071634460672"


def test_extract_league_id_accepts_sleeper_league_url() -> None:
    assert (
        extract_league_id("https://sleeper.com/leagues/1389328071634460672/matchup")
        == "1389328071634460672"
    )


def test_extract_league_id_rejects_missing_id() -> None:
    with pytest.raises(LeagueContextError, match="Could not find"):
        extract_league_id("https://sleeper.com/leagues/matchup")


def test_resolve_league_context_matches_team_name_exactly() -> None:
    context = resolve_league_context(
        FakeLeagueContextClient(),
        league_ref="https://sleeper.com/leagues/1389328071634460672/matchup",
        team_name="Little Johnson",
    )

    assert context == {
        "league_id": "1389328071634460672",
        "roster_id": 8,
        "owner_id": "1141086615987175424",
        "user_id": "1141086615987175424",
        "display_name": "bigboybhavs",
        "username": "bigboybhavs",
        "team_name": "Little Johnson",
        "matched_on": "team_name",
        "match_value": "Little Johnson",
        "env": {
            "SLEEPER_DEFAULT_LEAGUE_ID": "1389328071634460672",
            "SLEEPER_DEFAULT_ROSTER_ID": "8",
            "SLEEPER_DEFAULT_OWNER_ID": "1141086615987175424",
        },
    }


def test_resolve_league_context_matches_display_name() -> None:
    context = resolve_league_context(
        FakeLeagueContextClient(),
        league_ref="1389328071634460672",
        team_name="bigboybhavs",
    )

    assert context["roster_id"] == 8
    assert context["matched_on"] == "display_name"


def test_resolve_league_context_matches_roster_id() -> None:
    context = resolve_league_context(
        FakeLeagueContextClient(),
        league_ref="1389328071634460672",
        team_name="5",
    )

    assert context["roster_id"] == 5
    assert context["team_name"] == "DeVonta's Inferno"
    assert context["matched_on"] == "roster_id"


def test_resolve_league_context_allows_unique_partial_match() -> None:
    context = resolve_league_context(
        FakeLeagueContextClient(),
        league_ref="1389328071634460672",
        team_name="Inferno",
    )

    assert context["roster_id"] == 5
    assert context["matched_on"] == "team_name"


def test_resolve_league_context_rejects_ambiguous_partial_match() -> None:
    with pytest.raises(LeagueContextError, match="Multiple rosters matched"):
        resolve_league_context(
            FakeLeagueContextClient(),
            league_ref="1389328071634460672",
            team_name="manager",
        )


def test_resolve_league_context_lists_available_teams_when_no_match() -> None:
    with pytest.raises(LeagueContextError, match="Available teams"):
        resolve_league_context(
            FakeLeagueContextClient(),
            league_ref="1389328071634460672",
            team_name="missing",
        )


def test_render_context_env_quotes_string_values() -> None:
    context = resolve_league_context(
        FakeLeagueContextClient(),
        league_ref="1389328071634460672",
        team_name="5",
    )

    assert render_context_env(context, league_ref="https://example.test/leagues/1") == (
        "# Generated by sleeper configure-context.\n"
        'SLEEPER_DEFAULT_LEAGUE_URL="https://example.test/leagues/1"\n'
        "SLEEPER_DEFAULT_LEAGUE_ID=1389328071634460672\n"
        "SLEEPER_DEFAULT_ROSTER_ID=5\n"
        "SLEEPER_DEFAULT_OWNER_ID=owner-5\n"
        'SLEEPER_DEFAULT_TEAM_NAME="DeVonta\'s Inferno"\n'
        'SLEEPER_DEFAULT_DISPLAY_NAME="Opponent Manager"\n'
        'SLEEPER_DEFAULT_USERNAME="opponent"\n'
    )


def test_write_context_env_file_creates_parent_directory(tmp_path) -> None:
    context = resolve_league_context(
        FakeLeagueContextClient(),
        league_ref="1389328071634460672",
        team_name="Little Johnson",
    )
    env_file = tmp_path / "nested" / "sleeper-mcp.env"

    write_context_env_file(context, env_file, league_ref="1389328071634460672")

    assert "SLEEPER_DEFAULT_ROSTER_ID=8" in env_file.read_text(encoding="utf-8")


class FakeLeagueContextClient:
    def get_league_users(self, league_id: str) -> list[dict[str, object]]:
        return [
            {
                "user_id": "1141086615987175424",
                "display_name": "bigboybhavs",
                "username": "bigboybhavs",
                "metadata": {"team_name": "Little Johnson"},
            },
            {
                "user_id": "owner-5",
                "display_name": "Opponent Manager",
                "username": "opponent",
                "metadata": {"team_name": "DeVonta's Inferno"},
            },
            {
                "user_id": "owner-7",
                "display_name": "John Manager",
                "username": "john",
                "metadata": {"team_name": "Johnny Football"},
            },
        ]

    def get_rosters(self, league_id: str) -> list[dict[str, object]]:
        return [
            {"roster_id": 8, "owner_id": "1141086615987175424", "players": []},
            {"roster_id": 5, "owner_id": "owner-5", "players": []},
            {"roster_id": 7, "owner_id": "owner-7", "players": []},
        ]
